BA-273/os-reload
synergycp/scp-theme-admin pull request #874
Opened 2021-06-30 20:23 UTC by JakenPrime

added server settings group to the settings.json file

2021-07-06 05:56 UTC, cabloo requested changes

2021-07-06 05:56 UTC, cabloo commented on resources/assets/lang/en/settings.json
> +      "PLACEHOLDER": "Enter the OS Profile Billing ID to be loaded on Server wipe"
If this looks decent on the page, we should provide a suggestion to the user about how this is expected to be used, e.g.:

```suggestion
      "PLACEHOLDER": "Enter the OS Profile Billing ID to be loaded on Server wipe, e.g. format-quick to clear disk partition tables or format-slow to fully zero all disks."
```

2021-07-06 23:10 UTC, JakenPrime commented
![image](https://user-images.githubusercontent.com/13024300/124677124-06207200-de7d-11eb-9fa6-ac4a6868e7e9.png)

2021-07-19 19:22 UTC, cabloo approved these changes

2021-07-19 19:22 UTC, merged